services:
  - type: web
    name: hostel360-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /swagger-ui.html
    envVars:
      - key: JAVA_VERSION
        value: "25"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: dev
